title: Harrison Tolley's Blog
description: Things I've been thinking about, working on, and figuring out.
theme: jekyll-theme-cayman

permalink: /:title/

# enable latex
markdown: kramdown
kramdown:
  math_engine: mathjax