title: Harrison Tolley's Blog
description: Things I've been thinking about, working on, and figuring out.
theme: jekyll-theme-cayman
url: "https://harrisontolley.com"
author: Harrison Tolley

permalink: /:title/

# enable latex
markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag